### PR TITLE
Responsive layout for high-risk area page

### PR DESCRIPTION
**Pull request by cswbrian**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] i18n translation has been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ..., provide screenshots if necessary)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by yshing** [comment]
Ahh.. I also doing a Responsive version base on more updated dev..
image
@cswbrian 
I would try to combine both. :)

**Comment by cswbrian** [comment]
Yours' much cooler!

**Comment by cswbrian** [comment]
Let's use yours~

**Comment by cswbrian** [comment]
but you may need to take care of the datepicker as well.
 https://github.com/nandiheath/warsinhk/pull/118

**Pull request merged**
